### ISSUE TITLE
 About the definition of general rate-limit rule API.

### ISSUE THREAD

**Issue by wangfakang** [cncf/udpa#27]
I am investigating UDPA of the `rate-limit` related rules recently, and found a related discussion [here](https://github.com/envoyproxy/envoy/issues/10813), I hope it could be discussed in UDPA WG.  @lizan @htuch  @mattklein123 
thx

**Comment by htuch** [comment]
@wangfakang I think this is a good topic to cover, I'll work on scheduling a UDPA-WG meeting in the near future and we can include this.

**Comment by wangfakang** [comment]
@htuch Thanks your great work, I am also interested in this point, I look forward to communicate together, thank you.

**Comment by htuch** [comment]
Closing out issues in this repository, since the active repository is now https://github.com/cncf/xds.
