### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by kyessenov** [cncf/udpa#31]
Go expects a released version for go mod to produce reliable builds. It would be sufficient to make a tag with a name `v0.0.1`.

**Comment by htuch** [comment]
Done, see https://github.com/cncf/udpa/releases/tag/v0.0.1.

**Comment by kyessenov** [comment]
Can you add a tag go/v0.0.1 per https://golang.org/ref/mod#vcs-version? Don't ask me why go is so weird.
