### ISSUE TITLE
RFC process for UDPA

### ISSUE THREAD

**Issue by htuch** [cncf/udpa#33]
We've recently adopted [xDS transport next steps](https://docs.google.com/document/d/1zZav-IYxMO0mP2A7y5XHBa9v0eXyirw1CxrLLSUqWR8/edit) as plan-of-record for xDS transport evolution. This is effectively the UDPA transport protocol. I've just opened https://github.com/cncf/udpa/issues/32 to propose an addendum to clarify some behavior around context parameters.

I think at this point, rather than working with Google Docs and GitHub issues, it makes sense to switch to a process where we track changes in lightweight GitHub RFC docs. An example that I think will serve well is the [gRPC RFC](https://github.com/grpc/proposal#grpc-rfcs) process, aka gRFC. This has the advantage of provided a reference, a fairly lightweight review process, not too much boilerplate and allows us to focus discussions via PR review.

If this sounds reasonable, I can draft up a PR with a template and process for uRFCs (UDPA RFCs).

@markdroth @louiscryan @howardjohn @costinm @mattklein123 @envoyproxy/udpa-wg

**Comment by markdroth** [comment]
SGTM.

**Comment by mattklein123** [comment]
:+1:
