### ISSUE TITLE
Question: UDPA implemented using eBPF

### ISSUE THREAD

**Issue by mhausenblas** [cncf/udpa#36]
As [eBPF](https://ebpf.io/) enjoys increasing uptake, I was wondering if anyone has been looking into implementing UDPA using eBPF? I came across the [Dropbox engineering](https://dropbox.tech/infrastructure/how-we-migrated-dropbox-from-nginx-to-envoy) report on their migration story to Envoy and hence would be interested to learn what others see or think about this.

**Comment by htuch** [comment]
Closing this issue out as https://github.com/cncf/xds is now the active xDS working group list. FWIW I think there are efforts around xDS and eBPF.
