### ISSUE TITLE
Install repokitteh for wait commands

### ISSUE THREAD

**Issue by mattklein123** [cncf/udpa#5]

**Comment by mattklein123** [comment]
cc @itayd

**Comment by itayd** [comment]
this is in the cncf org - who manages it? they'll have to install the repokitteh app first.

**Comment by mattklein123** [comment]
cc @caniszczyk ^

**Comment by caniszczyk** [comment]
I need a link to install

**Comment by itayd** [comment]
@caniszczyk sent in slack

**Comment by caniszczyk** [comment]
done

**Comment by itayd** [comment]
Please reopen - repokitteh.star still need to be put in the root of the repo and configuration to be done on repokittah's side. I will do it tonight.

**Comment by itayd** [comment]
Please merge https://github.com/cncf/udpa/pull/6 to enable.
